spring:
  application:
    name: trade
  thymeleaf:
    prefix: classpath:/templates
    suffix: .jsp
    mode: HTML5
    encoding: UTF-8
    cache: false
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  datasource:
    primary:
      jdbc-url: jdbc:mysql://localhost:3306/rocketmq
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    secondary:
      jdbc-url: jdbc:mysql://localhost:3306/rocketmq2
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
server:
  port: 9090
mybatis:
  type-aliases-package: com.chz.pojo
  # mapper-locations: classpath*:mapper/**/*.xml

